CREATE DATABASE PPP_LOAN;

CREATE SCHEMA PUBLIC;

CREATE  TABLE PUBLIC.DIM_BORROWER ( 
	BORROWER_ID          integer NOT NULL   ,
	BORROWER_NAME        varchar(200)    ,
	BORROWER_ADDRESS     varchar(200)    ,
	BORROWER_CITY        varchar(100)    ,
	BORROWER_STATE       varchar(100)    ,
	BORROWER_ZIP         varchar(100)    ,
	RACE                 varchar(100)    ,
	ETHNICITY            varchar(100)    ,
	GENDER               varchar(100)    ,
	VETERAN              boolean    ,
	FRANCHISE_NAME       varchar(200)    ,
	NONPROFIT            boolean    ,
	BUSINESS_TYPE        varchar    ,
	BUSINESS_AGE_DESCRIPTION varchar(200)    ,
	JOBS_REPORTED        integer    ,
	CONSTRAINT PK_DIM_BORROWER PRIMARY KEY ( BORROWER_ID )
 );

CREATE  TABLE PUBLIC.DIM_DATE ( 
	DATE_ID              integer NOT NULL   ,
	YEAR_NUMBER          integer    ,
	MONTH_NUMBER         integer    ,
	QUARTER_NUMBER       integer    ,
	DAY_NUMBER           integer    ,
	HOUR_NUMBER          integer    ,
	ISHOLIDAY            boolean    ,
	DAY_NAME             varchar(100)    ,
	MONTH_NAME           varchar(100)    ,
	WEEK_OF_MONTH        integer    ,
	WEEK_OF_YEAR         integer    ,
	CONSTRAINT PK_DIM_DATE PRIMARY KEY ( DATE_ID )
 );

CREATE  TABLE PUBLIC.DIM_GEOGRAPHY ( 
	GEOFIPS              integer NOT NULL   ,
	GEO_NAME             varchar(100)    ,
	REGION               varchar(50)    ,
	PROJECT_COUNTY_NAME  varchar(200)    ,
	PROJECT_STATE        varchar(100)    ,
	CONSTRAINT PK_DIM_GEOGRAPHY PRIMARY KEY ( GEOFIPS )
 );

CREATE  TABLE PUBLIC.DIM_LOAN_STATUS ( 
	LOAN_STATUS_ID       integer NOT NULL   ,
	LOAN_STATUS          varchar(100)    ,
	CONSTRAINT PK_DIM_LOAN_STATUS PRIMARY KEY ( LOAN_STATUS_ID )
 );

CREATE  TABLE PUBLIC.DIM_NAICS ( 
	NAICS_CODE           integer NOT NULL   ,
	NAICS_TITLE          varchar(200)    ,
	DESCRIPTION          text    ,
	CONSTRAINT PK_NAICS_CODE PRIMARY KEY ( NAICS_CODE )
 );

CREATE  TABLE PUBLIC.DIM_ORIGINATING_LENDER ( 
	ORIGINATING_LENDER_ID integer NOT NULL   ,
	ORIGINATING_LENDER_LOCATION_ID integer    ,
	ORIGINATING_LENDER   varchar(200)    ,
	ORIGINATING_LENDER_CITY varchar(200)    ,
	ORIGINATING_LENDER_STATE varchar(100)    ,
	CONSTRAINT PK_DIM_ORIGINATING_LENDER PRIMARY KEY ( ORIGINATING_LENDER_ID )
 );

CREATE  TABLE PUBLIC.DIM_PROCESSING_METHOD ( 
	PROCESSING_METHOD_ID integer NOT NULL   ,
	PROCESSING_METHOD    varchar(100)    ,
	CONSTRAINT PK_DIM_PROCESSING_METHOD PRIMARY KEY ( PROCESSING_METHOD_ID )
 );

CREATE  TABLE PUBLIC.DIM_SBA_OFFICE ( 
	SBA_OFFICE_CODE      integer NOT NULL   ,
	CONSTRAINT PK_DIM_SBA_OFFICE PRIMARY KEY ( SBA_OFFICE_CODE )
 );

CREATE  TABLE PUBLIC.DIM_SERVICING_LENDER ( 
	SERVICING_LENDER_ID  integer NOT NULL   ,
	SERVICING_LENDER_LOCATION_ID integer    ,
	SERVICING_LENDER_NAME varchar(200)    ,
	SERVICING_LENDER_ADDRESS varchar(200)    ,
	SERVICING_LENDER_CITY varchar(100)    ,
	SERVICING_LENDER_STATE varchar(200)    ,
	SERVICING_LENDER_ZIP integer    ,
	CONSTRAINT PK_DIM_SERVICING_LENDER PRIMARY KEY ( SERVICING_LENDER_ID )
 );

CREATE  TABLE PUBLIC.DIM_TERM ( 
	TERM_ID              integer NOT NULL   ,
	TERM_MONTH           integer    ,
	CONSTRAINT PK_DIM_TERM PRIMARY KEY ( TERM_ID )
 );

CREATE  TABLE PUBLIC.FACTS_PPP ( 
	FACTS_ID             integer NOT NULL   ,
	LOAN_NUMBER          integer    ,
	NAICS_CODE           integer NOT NULL   ,
	GEOFIPS              integer NOT NULL   ,
	DATE_APPROVED_ID     integer NOT NULL   ,
	LOAN_STATUS_DATE_ID  integer NOT NULL   ,
	FORGIVENESS_DATE_ID  integer NOT NULL   ,
	BORROWER_ID          integer NOT NULL   ,
	ORIGINATING_LENDER_ID integer NOT NULL   ,
	SERVICING_LENDER_ID  integer NOT NULL   ,
	TERM_ID              integer NOT NULL   ,
	LOAN_STATUS_ID       integer NOT NULL   ,
	PROCESSING_METHOD_ID integer NOT NULL   ,
	SBA_OFFICE_CODE      integer NOT NULL   ,
	SBA_GUARANTY_PERCENTAGE double    ,
	INITIAL_APPROVAL_AMOUNT double    ,
	CURRENT_APPROVAL_AMOUNT double    ,
	UNDISBURSED_AMOUNT   double    ,
	FORGIVENESS_AMOUNT   double    ,
	CONSTRAINT PK_FACTS_PPP PRIMARY KEY ( FACTS_ID )
 );

ALTER TABLE PUBLIC.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_NAICS FOREIGN KEY ( NAICS_CODE ) REFERENCES PUBLIC.DIM_NAICS( NAICS_CODE ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_GEOGRAPHY FOREIGN KEY ( GEOFIPS ) REFERENCES PUBLIC.DIM_GEOGRAPHY( GEOFIPS ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_DATE FOREIGN KEY ( DATE_APPROVED_ID ) REFERENCES PUBLIC.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_DATE_0 FOREIGN KEY ( LOAN_STATUS_DATE_ID ) REFERENCES PUBLIC.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_DATE_1 FOREIGN KEY ( FORGIVENESS_DATE_ID ) REFERENCES PUBLIC.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_BORROWER FOREIGN KEY ( BORROWER_ID ) REFERENCES PUBLIC.DIM_BORROWER( BORROWER_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_ORIGINATING_LENDER FOREIGN KEY ( ORIGINATING_LENDER_ID ) REFERENCES PUBLIC.DIM_ORIGINATING_LENDER( ORIGINATING_LENDER_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_SERVICING_LENDER FOREIGN KEY ( SERVICING_LENDER_ID ) REFERENCES PUBLIC.DIM_SERVICING_LENDER( SERVICING_LENDER_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_TERM FOREIGN KEY ( TERM_ID ) REFERENCES PUBLIC.DIM_TERM( TERM_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_LOAN_STATUS FOREIGN KEY ( LOAN_STATUS_ID ) REFERENCES PUBLIC.DIM_LOAN_STATUS( LOAN_STATUS_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_PROCESSING_METHOD FOREIGN KEY ( PROCESSING_METHOD_ID ) REFERENCES PUBLIC.DIM_PROCESSING_METHOD( PROCESSING_METHOD_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PUBLIC.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_SBA_OFFICE FOREIGN KEY ( SBA_OFFICE_CODE ) REFERENCES PUBLIC.DIM_SBA_OFFICE( SBA_OFFICE_CODE ) ON DELETE NO ACTION ON UPDATE NO ACTION;
