CREATE SCHEMA ppp_loan;

CREATE  TABLE "ppp_loan_dw_lgl".ppp_loan.DIM_BORROWER ( 
	BORROWER_ID          integer NOT NULL   ,
	BORROWER_NAME        varchar(200)    ,
	BORROWER_ADDRESS     varchar(200)    ,
	BORROWER_CITY        varchar(200)    ,
	BORROWER_STATE       varchar(200)    ,
	BORROWER_ZIP         varchar(200)    ,
	RACE                 varchar(200)    ,
	ETHNICITY            varchar(200)    ,
	FRANCHISE_NAME       varchar(200)    ,
	GENDER               varchar(20)    ,
	VETERAN              boolean    ,
	NONPROFIT            boolean    ,
	BUSINESS_AGE_DESCRIPTION varchar(200)    ,
	JOBS_REPORTED        integer    ,
	BUSINESS_TYPE        varchar(200)    ,
	CONSTRAINT PK_ENTITYDIM_BORROWER PRIMARY KEY ( BORROWER_ID )
 );

CREATE  TABLE "ppp_loan_dw_lgl".ppp_loan.DIM_DATE ( 
	DATE_ID              integer NOT NULL   ,
	YEAR_NUMBER          integer    ,
	MONTH_NUMBER         integer    ,
	QUARTER_NUMBER       integer    ,
	DAY_NUMBER           integer    ,
	HOUR_NUMBER          integer    ,
	ISHOLIDAY            boolean    ,
	DAY_NAME             varchar(100)    ,
	MONTH_NAME           varchar(100)    ,
	WEEK_OF_MONTH        integer    ,
	WEEK_OF_YEAR         integer    ,
	CONSTRAINT PK_DIM_DATE_ID PRIMARY KEY ( DATE_ID )
 );

CREATE  TABLE "ppp_loan_dw_lgl".ppp_loan.DIM_GEOGRAPHY_ ( 
	GEOFIPS_ID           integer NOT NULL   ,
	GEO_NAME             varchar(100)    ,
	REGION               varchar(50)    ,
	PROJECT_COUNTY_NAME  varchar(255)    ,
	PROJECT_STATE        varchar(255)    ,
	CONSTRAINT PK_DIM_GEOGRAPHY_0 PRIMARY KEY ( GEOFIPS_ID )
 );

CREATE  TABLE "ppp_loan_dw_lgl".ppp_loan.DIM_LOAN_STATUS ( 
	LOAN_STATUS_ID       integer NOT NULL   ,
	LOAN_STATUS          varchar(50)    ,
	CONSTRAINT PK_DIM_LOAN_STATUS_ PRIMARY KEY ( LOAN_STATUS_ID )
 );

CREATE  TABLE "ppp_loan_dw_lgl".ppp_loan.DIM_NAICS ( 
	NAICS_CODE           integer NOT NULL   ,
	TITLE                varchar(100)    ,
	DESCRIPTION          varchar(250)    ,
	CONSTRAINT PK_DIM_NAICS PRIMARY KEY ( NAICS_CODE )
 );

CREATE  TABLE "ppp_loan_dw_lgl".ppp_loan.DIM_ORIGINATING_LENDER ( 
	ORIGINATING_LENDER_ID integer NOT NULL   ,
	ORIGINATING_LENDER_LOCATION_ID varchar(50)    ,
	ORIGINATING_LENDER   varchar(50)    ,
	ORIGINATING_LENDER_CITY varchar(50)    ,
	ORIGINATING_LENDER_STATE varchar(50)    ,
	CONSTRAINT PK_DIM_ORIGINATING_LENDER PRIMARY KEY ( ORIGINATING_LENDER_ID )
 );

CREATE  TABLE "ppp_loan_dw_lgl".ppp_loan.DIM_PROCESSING_METHOD ( 
	PROCESSING_METHOD_ID integer NOT NULL   ,
	PROCESSING_METHOD    varchar(50)    ,
	CONSTRAINT PK_DIM_PROCESSING_METHOD PRIMARY KEY ( PROCESSING_METHOD_ID )
 );

CREATE  TABLE "ppp_loan_dw_lgl".ppp_loan.DIM_SBA_OFFICE ( 
	SBA_OFFICE_CODE      integer NOT NULL   ,
	CONSTRAINT PK_DIM_SBA_OFFICE PRIMARY KEY ( SBA_OFFICE_CODE )
 );

CREATE  TABLE "ppp_loan_dw_lgl".ppp_loan.DIM_SERVICING_LENDER ( 
	SERVICING_LENDER_ID  integer NOT NULL   ,
	SERVICING_LENDER_LOCATION_ID integer    ,
	SERVICING_LENDER_NAME varchar(200)    ,
	SERVICING_LENDER_ADDRESS varchar(200)    ,
	SERVICING_LENDER_CITY varchar(200)    ,
	SERVICING_LENDER_STATE varchar(200)    ,
	SERVICING_LENDER_ZIP integer    ,
	CONSTRAINT PK_DIM_SERVICING_LENDER PRIMARY KEY ( SERVICING_LENDER_ID )
 );

CREATE  TABLE "ppp_loan_dw_lgl".ppp_loan.DIM_TERM ( 
	TERM_ID              integer NOT NULL   ,
	TERM_MONTH           integer    ,
	CONSTRAINT PK_DIM_TERM_ PRIMARY KEY ( TERM_ID )
 );

CREATE  TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ( 
	FACTS_ID             integer NOT NULL   ,
	NAICS_CODE           integer NOT NULL   ,
	DATE_APPROVED_ID     integer NOT NULL   ,
	LOAN_STATUS_DATE_ID  integer NOT NULL   ,
	FORGIVENESS_DATE_ID  integer NOT NULL   ,
	ORIGINATING_LENDER_ID integer NOT NULL   ,
	BORROWER_ID          integer NOT NULL   ,
	LOAN_NUMBER          integer    ,
	SERVICING_LENDER_ID  integer NOT NULL   ,
	TERM_ID              integer NOT NULL   ,
	LOAN_STATUS_ID       integer NOT NULL   ,
	PROCESSING_METHOD_ID integer NOT NULL   ,
	SBA_OFFICE_CODE      integer NOT NULL   ,
	SBA_GUARANTY_PERCENTAGE number    ,
	INITIAL_APPROVAL_AMOUNT number    ,
	CURRENT_APPROVAL_AMOUNT number    ,
	UNDISBURSED_AMOUNT   number    ,
	FORGIVENESS_AMOUNT   number    ,
	GEOFIPS_ID           integer NOT NULL   ,
	CONSTRAINT PK_FACTS_PPP PRIMARY KEY ( FACTS_ID )
 );

ALTER TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_SERVICING_LENDER FOREIGN KEY ( SERVICING_LENDER_ID ) REFERENCES "ppp_loan_dw_lgl".ppp_loan.DIM_SERVICING_LENDER( SERVICING_LENDER_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_ORIGINATING_LENDER FOREIGN KEY ( ORIGINATING_LENDER_ID ) REFERENCES "ppp_loan_dw_lgl".ppp_loan.DIM_ORIGINATING_LENDER( ORIGINATING_LENDER_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_DATE FOREIGN KEY ( DATE_APPROVED_ID ) REFERENCES "ppp_loan_dw_lgl".ppp_loan.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_NAICS FOREIGN KEY ( NAICS_CODE ) REFERENCES "ppp_loan_dw_lgl".ppp_loan.DIM_NAICS( NAICS_CODE ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_GEOGRAPHY FOREIGN KEY ( GEOFIPS_ID ) REFERENCES "ppp_loan_dw_lgl".ppp_loan.DIM_GEOGRAPHY_( GEOFIPS_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_BORROWER FOREIGN KEY ( BORROWER_ID ) REFERENCES "ppp_loan_dw_lgl".ppp_loan.DIM_BORROWER( BORROWER_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_SBA_OFFICE FOREIGN KEY ( SBA_OFFICE_CODE ) REFERENCES "ppp_loan_dw_lgl".ppp_loan.DIM_SBA_OFFICE( SBA_OFFICE_CODE ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_TERM FOREIGN KEY ( TERM_ID ) REFERENCES "ppp_loan_dw_lgl".ppp_loan.DIM_TERM( TERM_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_LOAN_STATUS FOREIGN KEY ( LOAN_STATUS_ID ) REFERENCES "ppp_loan_dw_lgl".ppp_loan.DIM_LOAN_STATUS( LOAN_STATUS_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_PROCESSING_METHOD FOREIGN KEY ( PROCESSING_METHOD_ID ) REFERENCES "ppp_loan_dw_lgl".ppp_loan.DIM_PROCESSING_METHOD( PROCESSING_METHOD_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_DATE_0 FOREIGN KEY ( LOAN_STATUS_DATE_ID ) REFERENCES "ppp_loan_dw_lgl".ppp_loan.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "ppp_loan_dw_lgl".ppp_loan.FACTS_PPP ADD CONSTRAINT FK_FACTS_PPP_DIM_DATE_1 FOREIGN KEY ( FORGIVENESS_DATE_ID ) REFERENCES "ppp_loan_dw_lgl".ppp_loan.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;
